overlay = "."
crate_src_path = ".."
maintainer = "Proxmox Support Team <support@proxmox.com>"

[source]
vcs_git = "git://git.proxmox.com/git/proxmox-apt.git"
vcs_browser = "https://git.proxmox.com/?p=proxmox-apt.git"
